config/routes.rb
Rails.application.routes.draw do
  resources :listing_images
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create, :edit, :show] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :listings
  resources :search, controller: "search", only: [:index]
  # resources :bookings, controller: "bookings"
  
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  root 'welcome#index'
  
  post '/search' => 'search#search'
  
  get '/bookings/:id/payment_details'=> "bookings#payment_details", as: :payment_details
  
  post '/bookings/:id/checkout' => 'bookings#checkout'
  
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  
  # get '/bookings/:id' => 'bookings#book', as: :book
  
  get '/bookings/:id/dates_confirmation' => 'bookings#dates_confirmation', as: :dates_confirmation
  
  get '/bookings/:id/book_check' => 'bookings#book_check', as: :book_check
  
  get '/bookings/:id/book_confirmation' => 'bookings#book_confirmation', as: :book_confirmation
  
  post '/bookings/:id/book_finalization' => 'bookings#book_finalization', as: :book_finalization
  
  # AJAX ROUTES
  
  post 'listings/:id/delete_photo' => 'listings#delete_photo'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/listing.rb
class Listing < ActiveRecord::Base

  acts_as_bookable time_type: :range, bookable_across_occurrences: true
  
  # mount_uploaders :photos, PhotoUploader
  
  require 'pg_search'
  include PgSearch
  multisearchable :against => [ :title, :description, :city, :country ]
  
  has_many :keyword_listings
  has_many :keywords, through: :keyword_listings
  has_many :listing_images
  accepts_nested_attributes_for :listing_images
  belongs_to :user
  
  scope :city, -> (city) { where( "city ILIKE :city", city: "%#{city}%" )}
  scope :price, -> (price) { where ( "price < ?" " #{price} ")}
  scope :guests, -> (guests) { where ( "guests >= ?" " #{guests} ")}
  scope :bedrooms, -> (bedrooms) { where ( "bedrooms >= ?" " #{bedrooms}" )}
  scope :bathrooms, -> (bathrooms) { where ("bathrooms >= ?" " #{bathrooms}")} 
    
    def self.search_cities(query)
      where("city ILIKE :city", city: "%#{query}%").distinct.map do |record|
        record.city
      end
    end
    
    def total_reviews
      Review.where(listing_id: self.id)
    end
    
    def rating
      rating = 0
      if total_reviews.count > 0
        total_reviews.each do |review|
          rating += review.rating
        end
        rating = rating / total_reviews.count
      end
    end
    
    def total_price(start_date, end_date)
      (self.price.to_i * booking_length(start_date, end_date)).to_i
    end
    
    def booking_length(start_date, end_date)
      end_date.to_date - start_date.to_date
    end
    
    def date_range(start_date, end_date)
      (start_date.to_date..end_date.to_date).map(&:to_s)
    end
    
    def update_listing_schedule
      current_listing.schedule = IceCube::Schedule.new(Date.today, duration: 365.days)
      current_listing.save
    end
    
    def date_within_bookable_range?(start_date, end_date)
      update_listing_schedule
      date_range(start_date, end_date).each do |date|
        if !current_listing.schedule.include?(date)
          false
        end
      end
      true
    end
  
    def is_available?(start_date, end_date)
      range = date_range(start_date, end_date)
      range.each do |date|
        date = date.to_date.strftime # Issue in different formats- converting to date then back to string gets all dates to same format
        if self.dates.include?(date)
          return false
        end
      true
      end
    end
    
    def reserve_dates(start_date, end_date)
      range = date_range(start_date, end_date)
      range.each do |date|
        self.dates << date
      end
      self.save
    end
    
    def host
      if self.user_id == nil
        "Mystery house!"
      else
        User.find(self.user_id).first_name
      end
    end
    
    def property_type
      
      property = Hash.new
      
      subtype_id = Property.find(self.property_id).property_subtype_id
      type_id = Property.find(self.property_id).property_type_id
      
      subtype = PropertySubtype.find(subtype_id).subtype
      type = PropertyType.find(type_id).property 
      
      property[:subtype] = subtype
      property[:type] = type
      
      property
      
    end
    
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  include ListingsHelper
  include ApplicationHelper
  
  before_action :set_listing, only: [:edit, :show, :book, :update]
  before_action :require_permission, only: [:edit, :create]

  def index
    @listings = Listing.where(nil)
    filtering_params(params).each do |k, v|
      @listings = @listings.public_send(k, v) if v.present?
    end
  end
  
  def new
    @listing = Listing.new
    # List all DBs that will be required to show available options for new listing.
    @property_types = PropertyType.all
    @property_subtypes = PropertySubtype.all
    @amenities = Amenity.all
    @safety_amenities = SafetyAmenity.all
    
    @listing_images = @listing.listing_images.build
    
  end
  
  def create
    @listing = Listing.new(listing_params)
    @listing.schedule = IceCube::Schedule.new(Date.today, duration: 365.days)
    @listing.user_id = current_user.id
    @listing.property_id = 6
 
    if @listing.save
      params[:listing_images]['image'].each do |image|
        @listing_image = @listing.listing_images.create!(:image => image)
      end
      flash[:notice] = "Listing added"
      redirect_to listing_path(@listing.id)
    else
      flash[:notice] = "Something went wrong- try again"
      redirect_to listings_path
    end
  end
  
  def destroy
  end
  
  def edit
    
  end
  
  def update
    photos = @listing.photos
    @listing.assign_attributes(listing_params)
    @listing.photos += photos
    if @listing.save
      redirect_to listing_path(@listing.id)
    end
  end
  
  def delete_photo(index)
    @listing = Listing.find(params[:id])
    @listing.photos[index].delete
    @listing.save
  end
  
  def show
    @listing_images = @listing.listing_images.all
  end
  
  private
  
  def set_listing
    @listing = current_listing
  end
  
  def listing_params
    # params.require(:listing).permit(:title, :description, :city, :country, :price, :guests, :beds, :bedrooms, :bathrooms, {photos: []})
    params.require(:listing).permit(:title, :description, :city, :country, :price, :guests, :beds, :bedrooms, :bathrooms, listing_images_attributes: [:id, :listing_id, :image])
  end
  
  def set_schedule(end_date)
    IceCube::Schedule.new(Date.today, duration: (end_date.to_date - Date.today).to_i.days)
  end
  
  
  def require_permission
    if !signed_in?
      flash[:notice] = "Oops, is this where you meant to go?"
      if params[:id]
        redirect_to listing_path
      else
        redirect_to listings_path
      end
    elsif params[:id]
      if current_user != current_listing.user
        flash[:notice] = "Oops, is this where you meant to go?"
        redirect_to listing_path
      end
    end
  end
  
  def filtering_params(params)
    params.slice(:city, :price, :guests, :bedrooms, :bathrooms)
  end
  
end

app/helpers/listings_helper.rb
module ListingsHelper

  # def get_listings(params)
      
  #   if (params[:check_in] && params[:check_out])
  #     @listings = []
  #     Listing.all.each do |listing|
        
  #       if listing.is_available?(params[:check_in], params[:check_out])
  #         @listings << listing
  #       end
  #     end

  #   elsif params[:guests]
  #     @listings = []
  #     Listing.all.each do |listing|
  #       if listing.guests >= params[:guests].to_i
  #         @listings << listing
  #       end
  #     end
      
      
  #   else
  #     @listings = Listing.all
      
  #   end

  #   @listings
  # end
  
end

app/views/listings/_bookingform.html.erb
<!--IMPLEMENT AJAX IN NEXT VERSION-->
<div id="booking-form">
  <p id="price-info"><span id="price">$<%=current_listing.price%></span> <span id="price-per">per night</span></p>
  <p>
    <span  class="rating">
      <% if current_listing.rating != nil %>
        <% current_listing.rating.times do %>
          <i class="fas fa-star"></i>
        <% end %>
      <% else %>
        No reviews yet, be the first to book.
      <% end %>
    </span>
    <span id="review-count"><sub><%= current_listing.total_reviews.count %> Reviews</sub></span>
  </p>
  <br>
  <hr class="hor-rule">
  <br>

  <%= form_tag dates_confirmation_path(current_listing.id), :method => :get do %> 
    <div class="field">
      <label>Check-in date:</label>
      <div class="control">
        <%= date_field_tag 'start_date', nil, :class => 'select booking-input' %>
      </div>
    </div>
    
    <div>
      <label>Check-out date:</label>
      <div class="control">
       <%= date_field_tag 'end_date', nil, :class => 'select booking-input' %>
      </div>
    </div>
    
    <div id="booking-dates-error-notice"><%= flash[:booking_error] %></div>
    
    <br>
    
    <div class="control">
      <%= submit_tag "Request to Book", :class => 'button', :id => 'booking-button' %>
    </div>
    <p class="form-footer">You won't be charged yet</p>
  <% end %>
</div>

app/views/listings/_detail.html.erb
 <% listing_type = listing.property_type %>
    <div class="listing">
      <div class="listing-image-content">
        <% if listing.photos.present? %>
          <%= image_tag(listing.photos[0].url) %>
        <% else %>
          <%= image_tag('https://images.unsplash.com/photo-1492889971304-ac16ab4a4a5a?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=058c56771e5c8d1f9adf38dc794f6e0e&auto=format&fit=crop&w=2553&q=80')%>
          <% end %>
      </div>
      
      <div class="listing-text-content">
        <p class="listing-additional-info"><%= listing_type[:subtype]%></p>
        <p class="listing-title"><%= listing.title %></p>
        <% if url_for(:only_path => true) == "/listings" %>
         <%= link_to "View more", listing_path(listing.id) %>
        <% end %>
        
        <% if signed_in? && (current_user.id == listing.user_id || current_user.superadmin?) %>
          <p><%= link_to "Edit this listing", edit_listing_path(listing.id) %></p>
        <% end %>
      </div>
    </div>

app/views/listings/_form.html.erb
<<<<<<< HEAD
<%= form_for(@listing, url: {action: "create"}, html: { :multipart => true }) do |f| %>
=======
>>>>>>> 4c9ebd12185de74b8b832b26dd2e8dc14090dc16

<div id = "new-listing-1">
  <p>Title: <%= f.text_field :title  %></p>
  <p>Description: <%= f.text_area :description %></p>
</div>    
<div id = "new-listing-2">
  <p>City: <%= f.text_field :city %></p>
  <p>Country: <%= f.text_field :country %></p>
</div>
<div id = "new-listing-3">
  <p>Price: <%= f.text_field :price %></p>
</div>
<div id = "new-listing-4">
</div>
<div id ="new-listing-5">
  <p>Guests: <%= f.text_field :guests %></p>
  <p>Beds: <%= f.text_field :beds %></p>
  <p>Bedrooms: <%= f.text_field :bedrooms %></p>
  <p>Bathrooms: <%= f.text_field :bathrooms %></p>
</div>
<div>
  <%= f.fields_for :listing_images do |i| %>
    <%= i.label :images %><br>
    <%= i.file_field :photo, :multiple => true, name: "listing_images[image][]" %>
  <% end %>
</div>

  <p><%= f.submit "Submit"%></p>  

app/views/listings/book.html.erb
<h4>Booking Page</h4>


<!--IMPLEMENT AJAX IN NEXT VERSION-->
<%= form_tag "/listings/#{current_listing.id}/book_check", :method => :get do %> 
  <p>
    Check-in date: 
    <%= date_field_tag 'start_date' %>
  </p>
  
  <p>
    Check-out date:
    <%= date_field_tag 'end_date' %>
  </p>
  
  <%= submit_tag("Check availability") %>
<% end %>

app/views/listings/book_confirmation.html.erb
<div id="booking-confirmation">
    <p>Check-in: <%= session[:start_date] %></p>
    <p>Check-out: <%= session[:end_date] %></p>
    <p>Listing: <%= current_listing.title %></p>
    
    <p>Everything look good? 
    <%= form_tag "/listings/#{current_listing.id}/book_success", :method => :post do %>
    <%= submit_tag("Confirm booking") %>
    <% end %></p>
</div>

app/views/listings/edit.html.erb
<div class="buffer">
  <h3>Edit listing</h3>
  
  <%= form_for @listing, url: {action: "update"} do |f| %>
    <%= render '/listings/form', f: f %>
  <% end %>
  
</div>

app/views/listings/index.html.erb
<script async defer src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_MAPS_KEY']%>&callback=myMap"
  type="text/javascript"></script>
  
<div class="column is-two-thirds">
  <div id="listings-container">
    <% @listings.each do |listing| %>
      <%= render "/listings/detail", listing: listing %>
    <% end %>
  </div>
</div>

<div class="column is-two-fifths buffer" id="map"></div>

app/views/listings/new.erb
<h3>Create new listing</h3>
<%= form_for @listing, url: {action: "create"} do |f| %>
  <%= render partial: '/listings/form', f: f %>
<% end %>

app/views/listings/show.html.erb
 <% listing_type = current_listing.property_type %>
 
  <div id="gallery-container">
    <i class="fas fa-plus" id="icon-add-photos"></i>
    <div id="gallery">
      <% if @listing.listing_images.present? %>
        <% @listing.listing_images.each_with_index do |img, index| %>
          <div class="image-container" index="<%=index%>">
            <%= image_tag(img.url, :class => "listing-image", :index => "#{index}") %>
            <i class="fas fa-trash-alt bottom-left"></i>
          </div>
        <% end %> 
      <% else %>
      <img src="https://images.unsplash.com/photo-1492889971304-ac16ab4a4a5a?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=058c56771e5c8d1f9adf38dc794f6e0e&auto=format&fit=crop&w=2553&q=80"></img>
      <img src="https://images.unsplash.com/photo-1492889971304-ac16ab4a4a5a?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=058c56771e5c8d1f9adf38dc794f6e0e&auto=format&fit=crop&w=2553&q=80"></img>
      <img src="https://images.unsplash.com/photo-1492889971304-ac16ab4a4a5a?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=058c56771e5c8d1f9adf38dc794f6e0e&auto=format&fit=crop&w=2553&q=80"></img>
      <img src="https://images.unsplash.com/photo-1492889971304-ac16ab4a4a5a?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=058c56771e5c8d1f9adf38dc794f6e0e&auto=format&fit=crop&w=2553&q=80"></img>
      <% end %>
    </div>
  </div>
  
<div id="show-container" class="columns">
  <div class="column is-three-fifths">
    <div id="listing-show-page"> 
      <p id="property-description">ENTIRE HOUSE</p>
      <p class="title" id="property-title"><%= current_listing.title %></p>
      <p id="property-type"><%= listing_type[:subtype]%> (<%=listing_type[:type]%>)</p>
      <% if signed_in? && (current_user.id == current_listing.user_id || current_user.superadmin?) %>
        <p><%= link_to "Edit this listing", edit_listing_path(current_listing.id) %></p>
      <% end %>
      <div id="listing-icons">
        <span><i class="fas fa-users"></i> <%=current_listing.guests%> guests</span>
        <span><i class="fas fa-lightbulb"></i> <%=current_listing.bedrooms%> bedrooms</span>
        <span><i class="fas fa-bed"></i> <%=current_listing.beds%> beds</span>
        <span><i class="fas fa-shower"></i> <%=current_listing.bathrooms%> bathrooms</span>
      </div>
      
      <div>
        <%= current_listing.description %>
      </div>
      
      <br>
      
      <hr>
      
      <div>
        <div id="review-header">
          <strong><%= current_listing.total_reviews.count %> Reviews </strong>
          <span class="rating">
            <% if current_listing.rating != nil  %>
              <% current_listing.rating.times do %>
                <i class="fas fa-star"></i>
              <% end %>
            <% else %>
                No reviews yet, be the first to book.
            <% end %>
          </span>
        </div>
        <% current_listing.total_reviews.each do |review| %>
        <div class="card-content">
          <div class="media">
            <div class="media-left">
              <figure class="image is-48x48">
                <img src="https://upload.wikimedia.org/wikipedia/commons/9/93/Default_profile_picture_%28male%29_on_Facebook.jpg">
              </figure>
            </div>
            
            <div class="media-content">
              <p class="review-name"><%= review.user.first_name %></p>
              <p class="review-date">February 2018</p>
            </div>    
          </div>
          
          <br>
          
          <div class="content">
            <%= review.text %>
          </div>
          
        </div>
        <hr class="hor-rule">
        <% end %>
      </div>
      
    </div>
  </div>
  
  <div class="column">
    <%= render "listings/bookingform" %>
  </div>

</div>