config/routes.rb
Rails.application.routes.draw do
  resources :listing_images
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create, :edit, :show] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :listings
  resources :search, controller: "search", only: [:index]
  # resources :bookings, controller: "bookings"
  
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  root 'welcome#index'
  
  post '/search' => 'search#search'
  
  get '/bookings/:id/payment_details'=> "bookings#payment_details", as: :payment_details
  
  post '/bookings/:id/checkout' => 'bookings#checkout'
  
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  
  # get '/bookings/:id' => 'bookings#book', as: :book
  
  get '/bookings/:id/dates_confirmation' => 'bookings#dates_confirmation', as: :dates_confirmation
  
  get '/bookings/:id/book_check' => 'bookings#book_check', as: :book_check
  
  get '/bookings/:id/book_confirmation' => 'bookings#book_confirmation', as: :book_confirmation
  
  post '/bookings/:id/book_finalization' => 'bookings#book_finalization', as: :book_finalization
  
  # AJAX ROUTES
  
  post 'listings/:id/delete_photo' => 'listings#delete_photo'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/listing_image.rb
class ListingImage < ActiveRecord::Base
  mount_uploader :image, PhotoUploader
  belongs_to :listing
end

app/controllers/listing_images_controller.rb
class ListingImagesController < ApplicationController
  before_action :set_listing_image, only: [:show, :edit, :update, :destroy]

  # GET /listing_images
  # GET /listing_images.json
  def index
    @listing_images = ListingImage.all
  end

  # GET /listing_images/1
  # GET /listing_images/1.json
  def show
    @listing_images = @listing.photos.all
  end

  # GET /listing_images/new
  def new
    @listing_image = ListingImage.new
  end

  # GET /listing_images/1/edit
  def edit
  end

  # POST /listing_images
  # POST /listing_images.json
  def create
    @listing_image = ListingImage.new(listing_image_params)

    respond_to do |format|
      if @listing_image.save
        format.html { redirect_to @listing_image, notice: 'Listing image was successfully created.' }
        format.json { render :show, status: :created, location: @listing_image }
      else
        format.html { render :new }
        format.json { render json: @listing_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listing_images/1
  # PATCH/PUT /listing_images/1.json
  def update
    respond_to do |format|
      if @listing_image.update(listing_image_params)
        format.html { redirect_to @listing_image, notice: 'Listing image was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing_image }
      else
        format.html { render :edit }
        format.json { render json: @listing_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listing_images/1
  # DELETE /listing_images/1.json
  def destroy
    @listing_image.destroy
    respond_to do |format|
      format.html { redirect_to listing_images_url, notice: 'Listing image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing_image
      @listing_image = ListingImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_image_params
      params.require(:listing_image).permit(:listing_id, :avatar)
    end
end

app/helpers/listing_images_helper.rb
module ListingImagesHelper
end

app/views/listing_images/_form.html.erb
<%= form_for(@listing_image) do |f| %>
  <% if @listing_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing_image.errors.count, "error") %> prohibited this listing_image from being saved:</h2>

      <ul>
      <% @listing_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :listing_id %><br>
    <%= f.number_field :listing_id %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.text_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listing_images/edit.html.erb
<h1>Editing Listing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing_image %> |
<%= link_to 'Back', listing_images_path %>

app/views/listing_images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Listing Images</h1>

<table>
  <thead>
    <tr>
      <th>Listing</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listing_images.each do |listing_image| %>
      <tr>
        <td><%= listing_image.listing_id %></td>
        <td><%= listing_image.avatar %></td>
        <td><%= link_to 'Show', listing_image %></td>
        <td><%= link_to 'Edit', edit_listing_image_path(listing_image) %></td>
        <td><%= link_to 'Destroy', listing_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing image', new_listing_image_path %>

app/views/listing_images/new.html.erb
<h1>New Listing Image</h1>

<%= render 'form' %>

<%= link_to 'Back', listing_images_path %>

app/views/listing_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Listing:</strong>
  <%= @listing_image.listing_id %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @listing_image.avatar %>
</p>

<%= link_to 'Edit', edit_listing_image_path(@listing_image) %> |
<%= link_to 'Back', listing_images_path %>