config/routes.rb
Rails.application.routes.draw do
  resources :listing_images
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "users", only: [:create, :edit, :show] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :listings
  resources :search, controller: "search", only: [:index]
  # resources :bookings, controller: "bookings"
  
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  root 'welcome#index'
  
  post '/search' => 'search#search'
  
  get '/bookings/:id/payment_details'=> "bookings#payment_details", as: :payment_details
  
  post '/bookings/:id/checkout' => 'bookings#checkout'
  
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  
  # get '/bookings/:id' => 'bookings#book', as: :book
  
  get '/bookings/:id/dates_confirmation' => 'bookings#dates_confirmation', as: :dates_confirmation
  
  get '/bookings/:id/book_check' => 'bookings#book_check', as: :book_check
  
  get '/bookings/:id/book_confirmation' => 'bookings#book_confirmation', as: :book_confirmation
  
  post '/bookings/:id/book_finalization' => 'bookings#book_finalization', as: :book_finalization
  
  # AJAX ROUTES
  
  post 'listings/:id/delete_photo' => 'listings#delete_photo'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_filtersbar.html.erb
<div class="navbar" id="filters-bar">

  <!--City Filter-->
  <div class="dropdown is-hoverable">
    <div class="dropdown-trigger">
      <button class="button" aria-haspopup="true" aria-controls="dropdown-menu">
        <span>City</span>
        <span class="icon is-small">
          <i class="fas fa-angle-down" aria-hidden="true"></i>
        </span>
      </button>
    </div>
    <div class="dropdown-menu" id="dropdown-menu" role="menu">
      <div class="dropdown-content">
        <%= form_for listings_path, method: :get do %>
          <%= text_field_tag 'city' %>
          <%= submit_tag("Search") %>        
        <% end %>
      </div>
    </div> 
  </div>
    
  <!--Dates Filter-->
  <div class="dropdown is-hoverable">
    <div class="dropdown-trigger">
      <button class="button" aria-haspopup="true" aria-controls="dropdown-menu">
        <span>Dates</span>
        <span class="icon is-small">
          <i class="fas fa-angle-down" aria-hidden="true"></i>
        </span>
      </button>
    </div>
    <div class="dropdown-menu" id="dropdown-menu" role="menu">
      <div class="dropdown-content">
        <%= form_for listings_path, method: :get do %>
          <%= date_field_tag 'check_in'%>
          <%= date_field_tag 'check_out'%>
          <%= hidden_field(:listing, :dates) %>
          <%= submit_tag("Search") %>        
        <% end %>
      </div>
    </div>
  </div>
  
  <!--Guests Filter-->
  <div class="dropdown is-hoverable">
    <div class="dropdown-trigger">
      <button class="button" aria-haspopup="true" aria-controls="dropdown-menu">
        <span>Guests</span>
        <span class="icon is-small">
          <i class="fas fa-angle-down" aria-hidden="true"></i>
        </span>
      </button>
    </div>
    <div class="dropdown-menu" id="dropdown-menu" role="menu">
      <div class="dropdown-content">
        <%= form_for listings_path, method: :get do %>
          <%= text_field_tag 'guests' %>
          <%= submit_tag("Search") %>        
        <% end %>
      </div>
    </div>
  </div>
    
  <!--Bedrooms Filter-->
  <div class="dropdown is-hoverable">
    <div class="dropdown-trigger">
      <button class="button" aria-haspopup="true" aria-controls="dropdown-menu">
        <span>Bedrooms</span>
        <span class="icon is-small">
          <i class="fas fa-angle-down" aria-hidden="true"></i>
        </span>
      </button>
    </div>
    <div class="dropdown-menu" id="dropdown-menu" role="menu">
      <div class="dropdown-content">
        <%= form_for listings_path, method: :get do %>
          <%= text_field_tag 'bedrooms' %>
          <%= submit_tag("Search") %>        
        <% end %>
      </div>
    </div>
  </div>
    
  <!--Bathrooms Filter-->
  <div class="dropdown is-hoverable">
    <div class="dropdown-trigger">
      <button class="button" aria-haspopup="true" aria-controls="dropdown-menu">
        <span>Bathrooms</span>
        <span class="icon is-small">
          <i class="fas fa-angle-down" aria-hidden="true"></i>
        </span>
      </button>
    </div>
    <div class="dropdown-menu" id="dropdown-menu" role="menu">
      <div class="dropdown-content">
        <%= form_for listings_path, method: :get do %>
          <%= text_field_tag 'bathrooms' %>
          <%= submit_tag("Search") %>        
        <% end %>
      </div>
    </div> 
  </div>
    
  <!--Price Filter-->
  <div class="dropdown is-hoverable">
    <div class="dropdown-trigger">
      <button class="button" aria-haspopup="true" aria-controls="dropdown-menu">
        <span>Price</span>
        <span class="icon is-small">
          <i class="fas fa-angle-down" aria-hidden="true"></i>
        </span>
      </button>
    </div>
    <div class="dropdown-menu" id="dropdown-menu" role="menu">
      <div class="dropdown-content">
        <%= form_for listings_path, method: :get do %>
          <%= text_field_tag 'price' %>
          <%= submit_tag("Search") %>        
        <% end %>
      </div>
    </div> 
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <link href="https://fonts.googleapis.com/css?family=Raleway:200,400,700,800" rel="stylesheet">
  <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
</head>
<body class="has-navbar-fixed-top">
  
  <!--FACEBOOK SDK-->
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&autoLogAppEvents=1&version=v2.12&appId=1040839342723303';
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
  </script>
  <!--FACEBOOK SDK-->
  
  <nav class="navbar is-fixed-top has-navbar-fixed-bottom" role="navigation" aria-label="main navigation">
    
    <div class="navbar-brand">
      <a class="navbar-item" href="/"><i class="fab fa-dribbble fa-2x airbnb-brand"></i></a>
      <div class="navbar-burger">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
    
    <div class="navbar-menu">
      <div class="navbar-start">
        <div class="navbar-item" id="search-form">
          <div class="field has-addons">
            
            <%= form_tag search_index_path, :method => :get  do %>
              <div class="control has-icons-right">
                <%= text_field_tag 'search', nil, placeholder: 'Miami, FL', class: 'input', list: "list" %>
                <datalist id="list"></datalist>
                <span class="icon is-small is-right">
                  <i class="fas fa-search fa-lg"></i>
                </span>
              </div>
            <% end %>
            
          </div>
        </div>
      </div>
      
      <div class="navbar-end">
        
        <div class="navbar-item" id="profile">
          <% if signed_in? %>
            <%= link_to "View Profile", "/users/show" %>
          <% end %>
        </div>
        
        <div class="navbar-item" id="sign-out-button">
          <% if signed_in? -%>
            <%= button_to t(".sign_out"), sign_out_path, method: :delete %>
          <% else -%>
            <%= link_to t(".sign_in"), sign_in_path %>
          <% end -%>
        </div>
        
      </div>
  </div>
  <% if url_for(:only_path => true) == "/listings" %>
    <%= render "/layouts/filtersbar" %>
  <% end %>
</nav>




  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>
  
  <%= yield %>
  <script src="https://maps.googleapis.com/maps/api/js?callback=myMap"></script>
</body>
</html>